// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static DoubleSolenoid* pneumaticsHood;
	static DoubleSolenoid* pneumaticsBayDoors;
	static DoubleSolenoid* pneumaticsShifter;
	static CANJaguar* shooterShooter1;
	static CANJaguar* shooterShooter2;
	static Encoder* shooterShootEncoder;
	static CANJaguar* intakeIntakeMotor;
	static CANJaguar* bADDeployLeft;
	static CANJaguar* bADDeployRight;
	static CANJaguar* bETCConveyor;
	static DigitalInput* bETCFrontLS;
	static DigitalInput* bETCMiddleLS;
	static DigitalInput* bETCBackLS;
	static CANJaguar* driveTrainFrontLeft;
	static CANJaguar* driveTrainFrontRight;
	static CANJaguar* driveTrainRearLeft;
	static CANJaguar* driveTrainRearRight;
	static RobotDrive* driveTrainRobotDrive41;
	static Encoder* driveTrainLeftDriveEncoder;
	static Encoder* driveTrainRightDriveEncoder;
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	static void init();
};
#endif
